[package]
name = "coreutils"
version = "0.1.0"
authors = ["Otto <otto@ot-to.nl>"]
edition = "2018"

[dependencies]
indicatif = "0.14.0"

[dependencies.clap]
version = "2.33.0"
default-features = false

[profile.release]
panic = "abort"
lto = true
